apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: argocd
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app: "grafana"
  type: ClusterIP
status:
  loadBalancer: {}