apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: simplegrafanadeploy
  url: https://github.com/egeo2021/argocdteste.git
  password: 985017Gmail
  username: egeo2021