apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: grafana
  namespace: argocd
spec: 
  destination: 
    namespace: grafana
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: simplegrafanadeploy/simplegrafanahelm
    repoURL: "https://github.com/bernardolankheet/argocd-simpleapp.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true