# Default values for zabbix-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: grafana/grafana
  imagePullPolicy: IfNotPresent
  tag: "8.3.11"

service:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000